version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui-frontend"
    schedule:
      interval: "weekly"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/okta-authorizer"
    schedule:
      interval: "weekly"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/lambda-layer/python"
    schedule:
      interval: "daily"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 5
